### ISSUE TITLE
Lists formatting

### ISSUE THREAD

**Issue by oscon** [getgrav/grav-theme-pinpress#3]
Hi, what's about the correct formatting of ordered (numbered) and unordered (bulleted) lists? Seems to be not implemented?
TIA

**Comment by hexplor** [comment]
I commited bunch of css fixes which should revert back to state where lists were properly supported. Please test and let me know. It's in the develop branch (not released yet). Thanks :) !

**Comment by oscon** [comment]
Seems not to working correctly:
After copying the theme, saving the page with the lists and clearing cache, the page crashes with the following Server Error:

Sorry, something went terribly wrong!
0 - An exception has been thrown during the rendering of a template ("array_keys() expects parameter 1 to be array, string given") in "partials/blog_item.html.twig" at line 103.
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.

Logfile:
[2015-12-28 09:27:13] grav.CRITICAL: An exception has been thrown during the rendering of a template ("array_keys() expects parameter 1 to be array, string given") in "partials/blog_item.html.twig" at line 103. - Trace: #0 E:\xampp\htdocs\grav-pinpress\vendor\twig\twig\lib\Twig\Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) #1 E:\xampp\htdocs\grav-pinpress\cache\twig\8b\8b7c730d50230aea917112962fc63b5fe1c4ad3c895b65a815b34e5014309789.php(118): Twig_Template->display(Array) #2 E:\xampp\htdocs\grav-pinpress\vendor\twig\twig\lib\Twig\Template.php(167): __TwigTemplate_b21142cb69e697b4c650dff8345fdda774ee414fcd23c97d00863c2cd2d2227a_1482088896->block_content(Array, Array) #3 E:\xampp\htdocs\grav-pinpress\cache\twig\84\8461e1a1c7b73a2fb2f9fc2a06948bbdca3bd932adc6f890e425201bc1a951a4.php(205): Twig_Template->displayBlock('content', Array, Array) #4 E:\xampp\htdocs\grav-pinpress\vendor\twig\twig\lib\Twig\Template.php(167): __TwigTemplate_b95db4ec63f5126e1a7e473dea7506dcd76c283926c8d8abe7ec407c3be2d6e9->block_body(Array, Array) #5 E:\xampp\htdocs\grav-pinpress\cache\twig\84\8461e1a1c7b73a2fb2f9fc2a06948bbdca3bd932adc6f890e425201bc1a951a4.php(61): Twig_Template->displayBlock('body', Array, Array) #6 E:\xampp\htdocs\grav-pinpress\vendor\twig\twig\lib\Twig\Template.php(381): __TwigTemplate_b95db4ec63f5126e1a7e473dea7506dcd76c283926c8d8abe7ec407c3be2d6e9->doDisplay(Array, Array) #7 E:\xampp\htdocs\grav-pinpress\vendor\twig\twig\lib\Twig\Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) #8 E:\xampp\htdocs\grav-pinpress\cache\twig\8b\8b7c730d50230aea917112962fc63b5fe1c4ad3c895b65a815b34e5014309789.php(81): Twig_Template->display(Array, Array) #9 E:\xampp\htdocs\grav-pinpress\vendor\twig\twig\lib\Twig\Template.php(381): __TwigTemplate_b21142cb69e697b4c650dff8345fdda774ee414fcd23c97d00863c2cd2d2227a_1482088896->doDisplay(Array, Array) #10 E:\xampp\htdocs\grav-pinpress\vendor\twig\twig\lib\Twig\Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) #11 E:\xampp\htdocs\grav-pinpress\cache\twig\8b\8b7c730d50230aea917112962fc63b5fe1c4ad3c895b65a815b34e5014309789.php(19): Twig_Template->display(Array) #12 E:\xampp\htdocs\grav-pinpress\vendor\twig\twig\lib\Twig\Template.php(381): __TwigTemplate_b21142cb69e697b4c650dff8345fdda774ee414fcd23c97d00863c2cd2d2227a->doDisplay(Array, Array) #13 E:\xampp\htdocs\grav-pinpress\vendor\twig\twig\lib\Twig\Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array) #14 E:\xampp\htdocs\grav-pinpress\vendor\twig\twig\lib\Twig\Template.php(366): Twig_Template->display(Array) #15 E:\xampp\htdocs\grav-pinpress\vendor\twig\twig\lib\Twig\Environment.php(347): Twig_Template->render(Array) #16 E:\xampp\htdocs\grav-pinpress\system\src\Grav\Common\Twig\Twig.php(322): Twig_Environment->render('blog.html.twig', Array) #17 E:\xampp\htdocs\grav-pinpress\system\src\Grav\Common\Grav.php(157): Grav\Common\Twig\Twig->processSite(NULL) #18 E:\xampp\htdocs\grav-pinpress\vendor\pimple\pimple\src\Pimple\Container.php(113): Grav\Common\Grav::Grav\Common{closure}(Object(Grav\Common\Grav)) #19 E:\xampp\htdocs\grav-pinpress\system\src\Grav\Common\Grav.php(257): Pimple\Container->offsetGet('output') #20 E:\xampp\htdocs\grav-pinpress\index.php(37): Grav\Common\Grav->process() #21 {main} [] []

**Comment by hexplor** [comment]
I didn't even touch blog_item.html.twig. I just added few fixes into css file: https://github.com/getgrav/grav-theme-pinpress/commit/bfddb85c95a976cca26b8f8772eeefe39bd6b179

**Comment by oscon** [comment]
Works all properly now!
